version: "3.8"
services:
  sb-app:
    build: .
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb+srv://matiasbasilotta:7gEgCD5FhZxRftDw@matiasmongo.1njl6vh.mongodb.net/pronosticos?retryWrites=true&w=majority
      - MONGODB_STATUS_HOST=mongodb
    container_name: "docker-app"
    ports:
      - 8080:8080
    networks:
      - red1
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - red1
volumes:
  mongo-data:
networks:
  red1:
    name: mired
    external: true