version: "3.8"
services:
  sb-app:
    build: .
    environment:
      - SERVER_PORT=8082
      - MONGODB_URI=mongodb://mongo_db:27017/pronosticos
      - MONGODB_STATUS_HOST=mongo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=pronosticos
      - DATABASE_NAME=pronosticos
    container_name: "app"
    ports:
      - 80:8082
    restart: always
   # networks:
    #  - red1
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:4.4.24
    container_name: "mongo"
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
   # networks:
    #  - red1
volumes:
  mongo-data:
#networks:
 # red1:
  #  name: mired
   # external: false