# fly.toml app configuration file generated for meteorologoplanet on 2023-08-05T19:09:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meteorologoplanet"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
